name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: prototype-gallery/package-lock.json
        
    - name: Install dependencies
      run: |
        cd prototype-gallery
        npm ci --legacy-peer-deps
        
    - name: Build React app
      run: |
        cd prototype-gallery
        npm run build
        
    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v4
      with:
        name: react-app
        path: prototype-gallery/dist
        
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: react-app
        path: ./deployment
        
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        package: ./deployment